services:
  # Backend API service
  - type: web
    name: ai-saas-platform-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /api/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: MONGO_URI
        value: # This will be manually set in the Render dashboard
      - key: STRIPE_API_KEY
        value: # This will be manually set in the Render dashboard
      - key: OPENAI_API_KEY
        value: # This will be manually set in the Render dashboard
        sync: false
      - key: STRIPE_SECRET_KEY
        value: # This will be manually set in the Render dashboard
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        value: # This will be manually set in the Render dashboard
        sync: false
    autoDeploy: true

  # Frontend web service
  - type: web
    name: ai-saas-platform-web
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-saas-platform-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
